Enables the option to change the credit card linked to a subscriptio. #187025550
r-martins/PagBank-WooCommerce pull request #12
Opened 2024-07-18 00:26 UTC by ligiasalzano

Rename the CreditCartTrial to CreditCardToken.

2024-07-18 01:51 UTC, r-martins commented
Além do erro reportado e exibido no frontend do campo fields, consegui trocar com sucesso por um cartão vencido. 
Mas depois apareceu a pagina com erro.

<img width="1149" alt="image" src="https://github.com/user-attachments/assets/74cae7c5-11e3-4796-b798-b3e2275a51b8">

2024-07-22 05:55 UTC, r-martins requested changes
Página de atualização de cartão (/my-account/rm-pagbank-subscriptions-update/9/) segue com erros..

Notice: Undefined variable: fields in /var/www/html/wp-content/plugins/pagbank-connect/src/templates/recurring/my-account/form-change-credit-card.php on line 43 Call Stack: 0.0090 368440 1. {main}() /var/www/html/index.php:0 0.0698 369088 2. require('/var/www/html/wp-blog-header.php') /var/www/html/index.php:17 2.2488 16868016 3. require_once('/var/www/html/wp-includes/template-loader.php') /var/www/html/wp-blog-header.php:19 2.2811 17238784 4. include('/var/www/html/wp-content/themes/storefront/page.php') /var/www/html/wp-includes/template-loader.php:106 3.1412 20156616 5. get_template_part(???, ???, ???) /var/www/html/wp-content/themes/storefront/page.php:24 3.1412 20157136 6. locate_template(???, ???, ???, ???) /var/www/html/wp-includes/general-template.php:206 3.1413 20157232 7. load_template(???, ???, ???) /var/www/html/wp-includes/template.php:745 3.1413 20157488 8. require('/var/www/html/wp-content/themes/storefront/content-page.php') /var/www/html/wp-includes/template.php:812 3.1428 20158304 9. do_action(???, ...variadic()) /var/www/html/wp-content/themes/storefront/content-page.php:18 3.1428 20158680 10. WP_Hook->do_action(???) /var/www/html/wp-includes/plugin.php:517 3.1428 20158680 11. WP_Hook->apply_filters(???, ???) /var/www/html/wp-includes/class-wp-hook.php:348 3.1437 20159840 12. storefront_page_content(???) /var/www/html/wp-includes/class-wp-hook.php:324 3.1437 20159840 13. the_content(???, ???) /var/www/html/wp-content/themes/storefront/inc/storefront-template-functions.php:352 3.1445 20159872 14. apply_filters(???, ???, ...variadic()) /var/www/html/wp-includes/post-template.php:256 3.1445 20160280 15. WP_Hook->apply_filters(???, ???) /var/www/html/wp-includes/plugin.php:205 3.1498 20086392 16. do_shortcode(???, ???) /var/www/html/wp-includes/class-wp-hook.php:324 3.1499 20092312 17. preg_replace_callback(???, ???, ???) /var/www/html/wp-includes/shortcodes.php:273 3.1499 20092792 18. do_shortcode_tag(???) /var/www/html/wp-includes/shortcodes.php:273 3.1500 20092792 19. WC_Shortcodes::my_account(???, ???, ???) /var/www/html/wp-includes/shortcodes.php:434 3.1500 20092792 20. WC_Shortcodes::shortcode_wrapper(???, ???, ???) /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php:115 3.1583 20109304 21. WC_Shortcode_My_Account::output(???) /var/www/html/wp-content/plugins/woocommerce/includes/class-wc-shortcodes.php:72 3.1583 20125816 22. WC_Shortcode_My_Account::my_account(???) /var/www/html/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php:72 3.1586 20140000 23. wc_get_template(???, ???, ???, ???) /var/www/html/wp-content/plugins/woocommerce/includes/shortcodes/class-wc-shortcode-my-account.php:123 3.1615 20140936 24. include('/var/www/html/wp-content/plugins/woocommerce/templates/myaccount/my-account.php') /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:345 3.2794 20598392 25. do_action(???, ...variadic()) /var/www/html/wp-content/plugins/woocommerce/templates/myaccount/my-account.php:34 3.2794 20598768 26. WP_Hook->do_action(???) /var/www/html/wp-includes/plugin.php:517 3.2794 20598768 27. WP_Hook->apply_filters(???, ???) /var/www/html/wp-includes/class-wp-hook.php:348 3.2799 20601264 28. woocommerce_account_content(???) /var/www/html/wp-includes/class-wp-hook.php:324 3.2799 20601360 29. do_action(???, ...variadic(???)) /var/www/html/wp-content/plugins/woocommerce/includes/wc-template-functions.php:3268 3.2799 20601736 30. WP_Hook->do_action(???) /var/www/html/wp-includes/plugin.php:517 3.2799 20601736 31. WP_Hook->apply_filters(???, ???) /var/www/html/wp-includes/class-wp-hook.php:348 3.2799 20602488 32. RM_PagBank\Connect\Recurring->addManageSubscriptionUpdateContent(???) /var/www/html/wp-includes/class-wp-hook.php:324 3.3206 20769088 33. wc_get_template(???, ???, ???, ???) /var/www/html/wp-content/plugins/pagbank-connect/src/Connect/Recurring.php:568 3.3306 20770688 34. include('/var/www/html/wp-content/plugins/pagbank-connect/src/templates/recurring/my-account/update-subscription.php') /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:345 3.3379 20772048 35. do_action(???, ...variadic(???)) /var/www/html/wp-content/plugins/pagbank-connect/src/templates/recurring/my-account/update-subscription.php:37 3.3379 20772424 36. WP_Hook->do_action(???) /var/www/html/wp-includes/plugin.php:517 3.3379 20772424 37. WP_Hook->apply_filters(???, ???) /var/www/html/wp-includes/class-wp-hook.php:348 3.3379 20773176 38. RM_PagBank\Connect\Recurring->subscriptionUpdateCreditCard(???) /var/www/html/wp-includes/class-wp-hook.php:324 3.3379 20773552 39. wc_get_template(???, ???, ???, ???) /var/www/html/wp-content/plugins/pagbank-connect/src/Connect/Recurring.php:672 3.3424 20776392 40. include('/var/www/html/wp-content/plugins/pagbank-connect/src/templates/recurring/my-account/form-change-credit-card.php') /var/www/html/wp-content/plugins/woocommerce/includes/wc-core-functions.php:345

2024-07-23 03:32 UTC, r-martins requested changes
Não consegui alterar o cartão. Apareceu "Não foi possível salvar o cartão. Tente novamente.".

Algumas coisas que notei:

1. No form do cartão, acho que nem todos os listeners e JS foram carregados. No frontend por exemplo, há detecção de bandeira, e converte letras mínusculas pra maiúsculas no nome do titular. Receio que faltou alguma coisa.

2. Nos logs, ao salvar a requisição, mais notices foram gravados.
PHP Notice:  Undefined index: code in /var/www/html/wp-content/plugins/pagbank-connect/src/Connect/Exception.php on line 42

ERROR Erro Connect:  - encrypted_is_invalid (encrypted)

2024-07-23 15:15 UTC, ligiasalzano commented
> Não consegui alterar o cartão. Apareceu "Não foi possível salvar o cartão. Tente novamente.".
> 
> Algumas coisas que notei:
> 
> 1. No form do cartão, acho que nem todos os listeners e JS foram carregados. No frontend por exemplo, há detecção de bandeira, e converte letras mínusculas pra maiúsculas no nome do titular. Receio que faltou alguma coisa.
> 2. Nos logs, ao salvar a requisição, mais notices foram gravados.
>    PHP Notice:  Undefined index: code in /var/www/html/wp-content/plugins/pagbank-connect/src/Connect/Exception.php on line 42
> 
> ERROR Erro Connect: - encrypted_is_invalid (encrypted)

@r-martins com qual cartão você testou? Esse erro eu não consegui pegar aqui.

2024-07-23 21:45 UTC, r-martins commented
Usei o famoso 4111111111111111 e 4539620659922097.

2024-07-25 04:45 UTC, r-martins requested changes
Já na home...
Notice: Undefined index: rm-pagbank-subscriptions-update in /var/www/html/wp-content/plugins/pagbank-connect/src/Connect/Gateway.php on line 393

2024-07-25 12:20 UTC, ligiasalzano commented
@r-martins, tem algo a mais errado. Parece que aí o JS não está funcionando direito. Aqui o transformer funciona desde o primeiro teste. Quando você acessa a página de troca de cartão, é exibido algum erro no console?
Vou instalar o módulo em outro WP pra ver se consigo replicar.

2024-07-29 03:48 UTC, r-martins commented
Sigo no aguardo do seu parecer. Vimos que dependendo do tema, o js não carrega. =/

2025-01-03 01:32 UTC, ligiasalzano commented
Esse PR foi feito com base em uma versão bem diferente do plugin. Então vou começar novamente a partir de uma nova branch. Esse PR aqui fica para fins de documentação e posterior consulta.

2025-01-03 01:32 UTC, closed without merging