Gateway Payment Methods Refactoring #188097195
r-martins/PagBank-WooCommerce pull request #15
Opened 2024-08-11 23:44 UTC by ligiasalzano

2024-08-11 23:44 UTC, ligiasalzano commented
@r-martins estou com um erro ao finalizar com o cartão de crédito. Mas parece ser algo do lado do PagBank. Segue o print: 
![Screenshot from 2024-08-11 20-19-23](https://github.com/user-attachments/assets/643d87ec-23d4-4b3c-9e47-b71ba4dd7a80)

Consegue confirmar, por favor?

2024-08-15 02:26 UTC, r-martins requested changes

2024-08-15 02:26 UTC, r-martins commented on src/Connect.php
> +            foreach ($settings as $key => $setting) {
ver se o settings é um array, pois em instalações novas, ao ativar o plugin temos o erro: Warning: foreach() argument must be of type array|object, bool given in /var/www/html/wp-content/plugins/pagbank-connect/src/Connect.php on line 285

2024-08-16 20:16 UTC, ligiasalzano commented on src/Connect.php
>          $isStandalone = Params::getConfig('standalone', 'yes') == 'yes';
Vou conferir.

2024-08-16 23:48 UTC, ligiasalzano commented on src/Connect/Standalone/CreditCard.php
> +        $payment_method = htmlspecialchars($_POST['ps_connect_method'], ENT_QUOTES, 'UTF-8');
O ps_connect_method sempre fica como boleto (mesmo antes da refatoração) pois temos 3 inputs com o mesmo name. O input do boleto é o que vem por último, por isso é ele quem fica atribuído. Nesta linha troquei o ps_connect_method por payment_method.

2024-08-16 23:58 UTC, ligiasalzano commented on src/Connect.php
>          $isStandalone = Params::getConfig('standalone', 'yes') == 'yes';
$isStandalone fica como true porque o valor defaul do getConfig é yes.

2024-08-20 02:35 UTC, merged